### PR TITLE
Index page

### PR DESCRIPTION
**Pull request by samullman**
Merge in updates over last few days

### CODE REVIEW

**Comment by dhyon** [comment]
```


11:50:42.863 | info  - Checking validity of types...
-- | --
11:50:48.829 | Failed to compile.
11:50:48.831 | ./pages/game/[id].tsx:6:27
11:50:48.831 | Type error: Property 'game' does not exist on type '{ children?: ReactNode; }'.
11:50:48.831 | 4 \| import { Box, Image, Heading } from '@chakra-ui/react';
11:50:48.831 | 5 \|
11:50:48.832 | > 6 \| const Home: NextPage = ({ game }) => {
11:50:48.832 | \|                           ^
11:50:48.832 | 7 \|   const {
11:50:48.832 | 8 \|     name,
11:50:48.832 | 9 \|     image,
11:50:48.861 | error Command failed with exit code 1.
11:50:48.861 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:50:48.881 | Error: Command "yarn run build" exited with 1

```

**Comment by samullman** [comment]
Maybe clear cache and redeploy -- working locally --

Could also be a Typescript error, not sure

**Comment by dhyon** [comment]
Try ```rm -rf node_modules package-lock.json``` to clear your installed modules. Run ```yarn install``` and then ```yarn run build```  to get instant feedback on your build instead of waiting for a Vercel deploy hook to finish. This'll shave a lot of time off your development cycles.

**Review by dhyon — APPROVED** [review]
great first batch of work Sam 👍 

Looks like you got things compiling for now. I'll cover you on the data prop retrieval from the backend.

**Pull request merged**
